/* eslint-disable @typescript-eslint/no-var-requires */
import { PrismaClient, Prisma } from '@prisma/client';
import * as bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

interface SeedProduct {
  sku: string;
  name: string;
  brand: string;
  categorySlug: string;
  priceCents: number;
  description: string;
  specifications: Record<string, string>;
  stock: number;
}

const notebooks: SeedProduct[] = [
  {
    sku: 'NB-ASUS-VIVOBOOK-16X',
    name: 'ASUS Vivobook 16X',
    brand: 'ASUS',
    categorySlug: 'notebooks',
    priceCents: 489900,
    description:
      'Notebook de 16 polegadas com Ryzen 7, ideal para desenvolvimento de software, Docker e multitarefa com muitas abas e containers.',
    specifications: {
      processor: 'AMD Ryzen 7 5800H (8 cores, 16 threads)',
      ram: '16 GB DDR4 (expansível até 32 GB)',
      storage: '512 GB NVMe SSD',
      screen: '16" WUXGA (1920x1200) IPS',
      gpu: 'NVIDIA GeForce RTX 3050 4 GB',
      weight: '1.9 kg',
      battery: '50 Wh, até 8 horas',
      connectivity: 'Wi-Fi 6, Bluetooth 5.2, USB-C, HDMI',
      os: 'Windows 11 Home',
    },
    stock: 14,
  },
  {
    sku: 'NB-DELL-LATITUDE-5440',
    name: 'Dell Latitude 5440',
    brand: 'Dell',
    categorySlug: 'notebooks',
    priceCents: 749900,
    description:
      'Notebook empresarial com processador Intel Core i7 de 13ª geração, robusto e silencioso, ideal para programação e trabalho remoto.',
    specifications: {
      processor: 'Intel Core i7-1355U',
      ram: '32 GB DDR5',
      storage: '1 TB NVMe SSD',
      screen: '14" FHD (1920x1080) antirreflexo',
      gpu: 'Intel Iris Xe',
      weight: '1.4 kg',
      battery: '57 Wh, até 12 horas',
      connectivity: 'Wi-Fi 6E, Thunderbolt 4, HDMI 2.0',
      os: 'Windows 11 Pro',
    },
    stock: 9,
  },
  {
    sku: 'NB-LENOVO-LEGION-5',
    name: 'Lenovo Legion 5',
    brand: 'Lenovo',
    categorySlug: 'notebooks',
    priceCents: 899900,
    description:
      'Notebook gamer de alto desempenho, ótimo para jogos, renderização e compilação pesada de código com 32 GB de RAM.',
    specifications: {
      processor: 'AMD Ryzen 7 7840HS',
      ram: '32 GB DDR5 5600MHz',
      storage: '1 TB NVMe SSD PCIe 4.0',
      screen: '15.6" QHD (2560x1440) 165Hz',
      gpu: 'NVIDIA RTX 4060 8 GB',
      weight: '2.4 kg',
      battery: '80 Wh, até 6 horas',
      connectivity: 'Wi-Fi 6, USB-C com DisplayPort, HDMI 2.1',
      os: 'Windows 11 Home',
    },
    stock: 7,
  },
  {
    sku: 'NB-MACBOOK-PRO-14',
    name: 'Apple MacBook Pro 14',
    brand: 'Apple',
    categorySlug: 'notebooks',
    priceCents: 1699900,
    description:
      'MacBook Pro com chip Apple M3 Pro, ideal para desenvolvimento iOS, machine learning e edição de vídeo profissional.',
    specifications: {
      processor: 'Apple M3 Pro (12 núcleos CPU, 18 núcleos GPU)',
      ram: '36 GB unificada',
      storage: '1 TB SSD',
      screen: '14.2" Liquid Retina XDR (3024x1964)',
      gpu: 'Apple GPU 18 núcleos',
      weight: '1.6 kg',
      battery: '72 Wh, até 18 horas',
      connectivity: 'Wi-Fi 6E, Thunderbolt 4 x3, HDMI, SDXC',
      os: 'macOS Sonoma',
    },
    stock: 5,
  },
  {
    sku: 'NB-MACBOOK-AIR-M3',
    name: 'Apple MacBook Air 13 M3',
    brand: 'Apple',
    categorySlug: 'notebooks',
    priceCents: 1199900,
    description:
      'MacBook Air ultraleve com chip M3, silencioso e com excelente autonomia, ótimo para programação web e mobile.',
    specifications: {
      processor: 'Apple M3 (8 núcleos CPU, 10 núcleos GPU)',
      ram: '16 GB unificada',
      storage: '512 GB SSD',
      screen: '13.6" Liquid Retina (2560x1664)',
      gpu: 'Apple GPU 10 núcleos',
      weight: '1.24 kg',
      battery: '52.6 Wh, até 15 horas',
      connectivity: 'Wi-Fi 6E, Thunderbolt 3 x2, MagSafe',
      os: 'macOS Sonoma',
    },
    stock: 11,
  },
  {
    sku: 'NB-ACER-NITRO-V16',
    name: 'Acer Nitro V 16',
    brand: 'Acer',
    categorySlug: 'notebooks',
    priceCents: 629900,
    description:
      'Notebook gamer de entrada com RTX 4050, bom custo-benefício para quem quer jogar e desenvolver em uma máquina só.',
    specifications: {
      processor: 'AMD Ryzen 5 7535HS',
      ram: '16 GB DDR5',
      storage: '512 GB NVMe SSD',
      screen: '16" WUXGA (1920x1200) 165Hz',
      gpu: 'NVIDIA RTX 4050 6 GB',
      weight: '2.5 kg',
      battery: '57 Wh, até 7 horas',
      connectivity: 'Wi-Fi 6, USB-C, HDMI 2.1',
      os: 'Windows 11 Home',
    },
    stock: 18,
  },
  {
    sku: 'NB-SAMSUNG-GALAXYBOOK4',
    name: 'Samsung Galaxy Book4',
    brand: 'Samsung',
    categorySlug: 'notebooks',
    priceCents: 549900,
    description:
      'Notebook fino com tela AMOLED, excelente para consumo de mídia, reuniões e desenvolvimento leve.',
    specifications: {
      processor: 'Intel Core i5-1340P',
      ram: '16 GB LPDDR5',
      storage: '512 GB NVMe SSD',
      screen: '15.6" FHD AMOLED',
      gpu: 'Intel Iris Xe',
      weight: '1.56 kg',
      battery: '54 Wh, até 14 horas',
      connectivity: 'Wi-Fi 6E, Thunderbolt 4, HDMI',
      os: 'Windows 11 Home',
    },
    stock: 12,
  },
  {
    sku: 'NB-HP-PAVILION-15',
    name: 'HP Pavilion 15',
    brand: 'HP',
    categorySlug: 'notebooks',
    priceCents: 359900,
    description:
      'Notebook acessível para estudantes e profissionais iniciantes, roda IDE e navegador com folga.',
    specifications: {
      processor: 'AMD Ryzen 5 5500U',
      ram: '8 GB DDR4',
      storage: '256 GB NVMe SSD',
      screen: '15.6" FHD IPS',
      gpu: 'AMD Radeon Graphics',
      weight: '1.7 kg',
      battery: '41 Wh, até 9 horas',
      connectivity: 'Wi-Fi 5, USB-C, HDMI 1.4',
      os: 'Windows 11 Home',
    },
    stock: 25,
  },
  {
    sku: 'NB-LENOVO-IDEAPAD-3',
    name: 'Lenovo IdeaPad 3',
    brand: 'Lenovo',
    categorySlug: 'notebooks',
    priceCents: 279900,
    description:
      'Notebook econômico para tarefas do dia a dia, estudos e programação básica.',
    specifications: {
      processor: 'Intel Core i3-1215U',
      ram: '8 GB DDR4',
      storage: '256 GB SSD',
      screen: '15.6" HD TN',
      gpu: 'Intel UHD Graphics',
      weight: '1.65 kg',
      battery: '38 Wh, até 7 horas',
      connectivity: 'Wi-Fi 5, USB-C, HDMI',
      os: 'Windows 11 Home',
    },
    stock: 30,
  },
  {
    sku: 'NB-GIGABYTE-AERO-14',
    name: 'Gigabyte Aero 14 OLED',
    brand: 'Gigabyte',
    categorySlug: 'notebooks',
    priceCents: 1049900,
    description:
      'Notebook de criação com tela OLED 2.8K calibrada, ideal para designers e desenvolvedores que valorizam cor.',
    specifications: {
      processor: 'Intel Core i7-13700H',
      ram: '32 GB DDR5',
      storage: '1 TB NVMe SSD',
      screen: '14" QHD+ OLED (2880x1800) 90Hz',
      gpu: 'NVIDIA RTX 4060 8 GB',
      weight: '1.6 kg',
      battery: '63 Wh, até 10 horas',
      connectivity: 'Wi-Fi 6E, Thunderbolt 4, HDMI 2.1',
      os: 'Windows 11 Pro',
    },
    stock: 4,
  },
  {
    sku: 'NB-THINKPAD-T14-G5',
    name: 'Lenovo ThinkPad T14 Gen 5',
    brand: 'Lenovo',
    categorySlug: 'notebooks',
    priceCents: 899900,
    description:
      'ThinkPad de última geração com teclado lendário e chassis em fibra de carbono, padrão-ouro corporativo para desenvolvedores.',
    specifications: {
      processor: 'Intel Core Ultra 7 155U',
      ram: '32 GB DDR5',
      storage: '1 TB NVMe SSD',
      screen: '14" WUXGA (1920x1200) 100% sRGB',
      gpu: 'Intel Arc Graphics',
      weight: '1.37 kg',
      battery: '52.5 Wh, até 15 horas',
      connectivity: 'Wi-Fi 6E, Thunderbolt 4 x2, HDMI 2.1, Ethernet',
      os: 'Windows 11 Pro',
    },
    stock: 8,
  },
  {
    sku: 'NB-DELL-XPS-13',
    name: 'Dell XPS 13 Plus',
    brand: 'Dell',
    categorySlug: 'notebooks',
    priceCents: 999900,
    description:
      'Notebook premium ultracompacto com design futurista, tela InfinityEdge e desempenho de sobra para desenvolvimento.',
    specifications: {
      processor: 'Intel Core i7-1360P',
      ram: '32 GB LPDDR5',
      storage: '1 TB NVMe SSD',
      screen: '13.4" FHD+ (1920x1200) InfinityEdge',
      gpu: 'Intel Iris Xe',
      weight: '1.26 kg',
      battery: '55 Wh, até 13 horas',
      connectivity: 'Wi-Fi 6E, Thunderbolt 4 x2',
      os: 'Windows 11 Home',
    },
    stock: 6,
  },
  {
    sku: 'NB-ASUS-ROG-STRIX-G16',
    name: 'ASUS ROG Strix G16',
    brand: 'ASUS',
    categorySlug: 'notebooks',
    priceCents: 949900,
    description:
      'Notebook gamer com Intel i9 e RTX 4070, máxima potência para compilação, simulação e jogos em alta.',
    specifications: {
      processor: 'Intel Core i9-13980HX (24 núcleos)',
      ram: '32 GB DDR5 4800MHz',
      storage: '1 TB NVMe SSD PCIe 4.0',
      screen: '16" QHD+ (2560x1600) 240Hz',
      gpu: 'NVIDIA RTX 4070 8 GB',
      weight: '2.5 kg',
      battery: '90 Wh, até 5 horas',
      connectivity: 'Wi-Fi 6E, Thunderbolt 4, HDMI 2.1',
      os: 'Windows 11 Home',
    },
    stock: 6,
  },
  {
    sku: 'NB-POSITIVO-VISION',
    name: 'Positivo Vision R15',
    brand: 'Positivo',
    categorySlug: 'notebooks',
    priceCents: 219900,
    description:
      'Notebook básico brasileiro com custo acessível, ideal para navegação, pacote office e aprendizado de programação.',
    specifications: {
      processor: 'Intel Celeron N4020',
      ram: '8 GB DDR4',
      storage: '256 GB SSD',
      screen: '15.6" HD',
      gpu: 'Intel UHD Graphics 600',
      weight: '1.9 kg',
      battery: '35 Wh, até 6 horas',
      connectivity: 'Wi-Fi 5, HDMI, USB-C',
      os: 'Windows 11 Home',
    },
    stock: 40,
  },
  {
    sku: 'NB-MSI-PULSE-GL66',
    name: 'MSI Pulse GL66',
    brand: 'MSI',
    categorySlug: 'notebooks',
    priceCents: 729900,
    description:
      'Notebook gamer com RTX 4060 e 144Hz, bom equilíbrio entre preço e desempenho para games e dev.',
    specifications: {
      processor: 'Intel Core i7-12700H',
      ram: '16 GB DDR5',
      storage: '512 GB NVMe SSD',
      screen: '15.6" FHD (1920x1080) 144Hz',
      gpu: 'NVIDIA RTX 4060 8 GB',
      weight: '2.25 kg',
      battery: '53.5 Wh, até 6 horas',
      connectivity: 'Wi-Fi 6, USB-C, HDMI 2.1',
      os: 'Windows 11 Home',
    },
    stock: 10,
  },
  {
    sku: 'NB-LG-GRAM-16',
    name: 'LG Gram 16',
    brand: 'LG',
    categorySlug: 'notebooks',
    priceCents: 849900,
    description:
      'Notebook ultraleve de 1.19 kg com tela 16" 2K, autonomia de até 20 horas — perfeito para devs que vivem viajando.',
    specifications: {
      processor: 'Intel Core i7-1360P',
      ram: '32 GB LPDDR5',
      storage: '1 TB NVMe SSD',
      screen: '16" WQXGA (2560x1600) IPS 100% DCI-P3',
      gpu: 'Intel Iris Xe',
      weight: '1.19 kg',
      battery: '80 Wh, até 20 horas',
      connectivity: 'Wi-Fi 6E, Thunderbolt 4 x2, HDMI',
      os: 'Windows 11 Home',
    },
    stock: 7,
  },
  {
    sku: 'NB-AVITA-PURA-14',
    name: 'Avita Pura 14',
    brand: 'Avita',
    categorySlug: 'notebooks',
    priceCents: 189900,
    description:
      'Notebook leve e barato para uso essencial, bom primeiro computador para estudantes.',
    specifications: {
      processor: 'Intel Celeron N4500',
      ram: '4 GB DDR4',
      storage: '128 GB eMMC',
      screen: '14" HD',
      gpu: 'Intel UHD Graphics',
      weight: '1.4 kg',
      battery: '36 Wh, até 8 horas',
      connectivity: 'Wi-Fi 5, HDMI, USB-C',
      os: 'Windows 11 Home S',
    },
    stock: 22,
  },
  {
    sku: 'NB-RAZER-BLADE-15',
    name: 'Razer Blade 15',
    brand: 'Razer',
    categorySlug: 'notebooks',
    priceCents: 1499900,
    description:
      'Notebook gamer premium em chassis de alumínio com RTX 4080, referência de design e desempenho.',
    specifications: {
      processor: 'Intel Core i9-13900H',
      ram: '32 GB DDR5',
      storage: '1 TB NVMe SSD',
      screen: '15.6" QHD (2560x1440) 240Hz',
      gpu: 'NVIDIA RTX 4080 12 GB',
      weight: '2.01 kg',
      battery: '80 Wh, até 6 horas',
      connectivity: 'Wi-Fi 6E, Thunderbolt 4, HDMI 2.1',
      os: 'Windows 11 Home',
    },
    stock: 3,
  },
  {
    sku: 'NB-ASUS-TUF-F15',
    name: 'ASUS TUF Gaming F15',
    brand: 'ASUS',
    categorySlug: 'notebooks',
    priceCents: 559900,
    description:
      'Notebook gamer resistente com padrão militar, excelente para estudantes de TI que também querem jogar.',
    specifications: {
      processor: 'Intel Core i5-12500H',
      ram: '16 GB DDR4',
      storage: '512 GB NVMe SSD',
      screen: '15.6" FHD (1920x1080) 144Hz',
      gpu: 'NVIDIA RTX 3050 4 GB',
      weight: '2.3 kg',
      battery: '56 Wh, até 8 horas',
      connectivity: 'Wi-Fi 6, USB-C, HDMI 2.0',
      os: 'Windows 11 Home',
    },
    stock: 16,
  },
  {
    sku: 'NB-MOTILE-14',
    name: 'Motile M142',
    brand: 'Motile',
    categorySlug: 'notebooks',
    priceCents: 249900,
    description:
      'Notebook acessível com Ryzen 5 e tela FHD, ótimo custo-benefício para programação de entrada.',
    specifications: {
      processor: 'AMD Ryzen 5 3450U',
      ram: '16 GB DDR4',
      storage: '256 GB NVMe SSD',
      screen: '14" FHD (1920x1080)',
      gpu: 'AMD Radeon Vega 8',
      weight: '1.4 kg',
      battery: '45 Wh, até 9 horas',
      connectivity: 'Wi-Fi 5, USB-C, HDMI',
      os: 'Windows 11 Home',
    },
    stock: 20,
  },
];

const smartphones: SeedProduct[] = [
  {
    sku: 'SM-SAMSUNG-S24ULTRA',
    name: 'Samsung Galaxy S24 Ultra',
    brand: 'Samsung',
    categorySlug: 'smartphones',
    priceCents: 949900,
    description:
      'Flagship com câmera de 200MP, S Pen, tela 6.8" QHD+ e 7 anos de atualizações. Melhor câmera e bateria da linha Galaxy.',
    specifications: {
      screen: '6.8" Dynamic AMOLED 2X QHD+ 120Hz',
      processor: 'Snapdragon 8 Gen 3 for Galaxy',
      ram: '12 GB',
      storage: '512 GB',
      cameraMain: '200 MP (OIS)',
      cameraUltrawide: '12 MP',
      cameraTelephoto: '10 MP (3x) + 50 MP (5x)',
      frontCamera: '12 MP',
      battery: '5000 mAh, 45W',
      os: 'Android 14 (One UI 6.1)',
      weight: '232 g',
      protection: 'IP68, Gorilla Glass Armor',
    },
    stock: 15,
  },
  {
    sku: 'SM-APPLE-IPHONE15PRO',
    name: 'Apple iPhone 15 Pro',
    brand: 'Apple',
    categorySlug: 'smartphones',
    priceCents: 1099900,
    description:
      'iPhone premium com chip A17 Pro, titânio, câmera principal de 48MP com modo ProRAW e vídeo ProRes.',
    specifications: {
      screen: '6.1" Super Retina XDR OLED 120Hz',
      processor: 'Apple A17 Pro',
      ram: '8 GB',
      storage: '256 GB',
      cameraMain: '48 MP (f/1.78)',
      cameraUltrawide: '12 MP',
      cameraTelephoto: '12 MP (3x)',
      frontCamera: '12 MP TrueDepth',
      battery: '3274 mAh, até 23h de vídeo',
      os: 'iOS 17',
      weight: '187 g',
      protection: 'IP68, titânio grau 5',
    },
    stock: 12,
  },
  {
    sku: 'SM-XIAOMI-14',
    name: 'Xiaomi 14',
    brand: 'Xiaomi',
    categorySlug: 'smartphones',
    priceCents: 549900,
    description:
      'Compacto flagship com Leica, Snapdragon 8 Gen 3 e tela 1.5K de 120Hz, excelente para fotografia.',
    specifications: {
      screen: '6.36" LTPO AMOLED 1.5K 120Hz',
      processor: 'Snapdragon 8 Gen 3',
      ram: '12 GB',
      storage: '256 GB',
      cameraMain: '50 MP Leica (f/1.6)',
      cameraUltrawide: '50 MP',
      cameraTelephoto: '50 MP (3.2x)',
      frontCamera: '32 MP',
      battery: '4610 mAh, 90W',
      os: 'Android 14 (HyperOS)',
      weight: '193 g',
      protection: 'IP68, Gorilla Glass Victus',
    },
    stock: 20,
  },
  {
    sku: 'SM-MOTOROLA-EDGE50PRO',
    name: 'Motorola Edge 50 Pro',
    brand: 'Motorola',
    categorySlug: 'smartphones',
    priceCents: 399900,
    description:
      'Moto com tela pOLED de 144Hz, câmera de 50MP com IA e carregamento turbo de 125W.',
    specifications: {
      screen: '6.7" pOLED FHD+ 144Hz',
      processor: 'Snapdragon 7 Gen 3',
      ram: '12 GB',
      storage: '256 GB',
      cameraMain: '50 MP OIS',
      cameraUltrawide: '13 MP',
      cameraTelephoto: '10 MP (3x)',
      frontCamera: '50 MP',
      battery: '4500 mAh, 125W turbo',
      os: 'Android 14',
      weight: '186 g',
      protection: 'IP68, Gorilla Glass 5',
    },
    stock: 25,
  },
  {
    sku: 'SM-GOOGLE-PIXEL9PRO',
    name: 'Google Pixel 9 Pro',
    brand: 'Google',
    categorySlug: 'smartphones',
    priceCents: 799900,
    description:
      'Pixel com IA de ponta, câmera computacional líder e 7 anos de atualizações do Android.',
    specifications: {
      screen: '6.3" LTPO OLED QHD+ 120Hz',
      processor: 'Google Tensor G4',
      ram: '16 GB',
      storage: '256 GB',
      cameraMain: '50 MP (f/1.68)',
      cameraUltrawide: '48 MP',
      cameraTelephoto: '48 MP (5x)',
      frontCamera: '42 MP',
      battery: '4700 mAh, 27W',
      os: 'Android 15',
      weight: '199 g',
      protection: 'IP68, Gorilla Glass Victus 2',
    },
    stock: 10,
  },
  {
    sku: 'SM-SAMSUNG-A55',
    name: 'Samsung Galaxy A55 5G',
    brand: 'Samsung',
    categorySlug: 'smartphones',
    priceCents: 249900,
    description:
      'Intermediário premium com tela Super AMOLED, câmera de 50MP e ótima bateria — o queridinho custo-benefício.',
    specifications: {
      screen: '6.6" Super AMOLED FHD+ 120Hz',
      processor: 'Exynos 1480',
      ram: '8 GB',
      storage: '256 GB (microSD)',
      cameraMain: '50 MP OIS',
      cameraUltrawide: '12 MP',
      cameraMacro: '5 MP',
      frontCamera: '32 MP',
      battery: '5000 mAh, 25W',
      os: 'Android 14 (One UI 6.1)',
      weight: '213 g',
      protection: 'IP67, Gorilla Glass Victus+',
    },
    stock: 35,
  },
  {
    sku: 'SM-MOTOROLA-G84',
    name: 'Motorola Moto G84',
    brand: 'Motorola',
    categorySlug: 'smartphones',
    priceCents: 169900,
    description:
      'Moto G com tela pOLED 120Hz, bateria de 5000mAh e Android limpo, excelente custo-benefício.',
    specifications: {
      screen: '6.55" pOLED FHD+ 120Hz',
      processor: 'Snapdragon 695',
      ram: '8 GB',
      storage: '256 GB (microSD)',
      cameraMain: '50 MP OIS',
      cameraUltrawide: '8 MP',
      frontCamera: '16 MP',
      battery: '5000 mAh, 30W',
      os: 'Android 14',
      weight: '166 g',
      protection: 'IP54',
    },
    stock: 40,
  },
  {
    sku: 'SM-APPLE-IPHONE13',
    name: 'Apple iPhone 13',
    brand: 'Apple',
    categorySlug: 'smartphones',
    priceCents: 399900,
    description:
      'iPhone com chip A15, câmera dupla de 12MP e excelente bateria — o clássico equilibrado.',
    specifications: {
      screen: '6.1" Super Retina XDR OLED',
      processor: 'Apple A15 Bionic',
      ram: '4 GB',
      storage: '128 GB',
      cameraMain: '12 MP (f/1.6)',
      cameraUltrawide: '12 MP',
      frontCamera: '12 MP',
      battery: '3240 mAh',
      os: 'iOS 17',
      weight: '174 g',
      protection: 'IP68, Ceramic Shield',
    },
    stock: 22,
  },
  {
    sku: 'SM-XIAOMI-REDMINOTE13',
    name: 'Xiaomi Redmi Note 13 Pro',
    brand: 'Xiaomi',
    categorySlug: 'smartphones',
    priceCents: 199900,
    description:
      'Redmi com câmera de 200MP, tela AMOLED de 120Hz e carregamento rápido de 67W.',
    specifications: {
      screen: '6.67" AMOLED FHD+ 120Hz',
      processor: 'Snapdragon 7s Gen 2',
      ram: '8 GB',
      storage: '256 GB (microSD)',
      cameraMain: '200 MP OIS',
      cameraUltrawide: '8 MP',
      cameraMacro: '2 MP',
      frontCamera: '16 MP',
      battery: '5100 mAh, 67W',
      os: 'Android 13 (MIUI 14)',
      weight: '187 g',
      protection: 'IP54, Gorilla Glass Victus',
    },
    stock: 38,
  },
  {
    sku: 'SM-ASUS-ROGPHONE8',
    name: 'ASUS ROG Phone 8',
    brand: 'ASUS',
    categorySlug: 'smartphones',
    priceCents: 749900,
    description:
      'Gamer phone com Snapdragon 8 Gen 3, tela de 165Hz, gatilhos de toque e refrigeração para gaming.',
    specifications: {
      screen: '6.78" AMOLED FHD+ 165Hz',
      processor: 'Snapdragon 8 Gen 3',
      ram: '16 GB',
      storage: '512 GB',
      cameraMain: '50 MP (gimbal)',
      cameraUltrawide: '13 MP',
      cameraTelephoto: '32 MP (3x)',
      frontCamera: '32 MP',
      battery: '5500 mAh, 65W',
      os: 'Android 14 (ROG UI)',
      weight: '225 g',
      protection: 'IP68',
    },
    stock: 8,
  },
  {
    sku: 'SM-NOTHING-PHONE2A',
    name: 'Nothing Phone (2a)',
    brand: 'Nothing',
    categorySlug: 'smartphones',
    priceCents: 219900,
    description:
      'Design transparente com glyph lights, Android puro e câmera de 50MP com estabilização.',
    specifications: {
      screen: '6.7" AMOLED FHD+ 120Hz',
      processor: 'MediaTek Dimensity 7200 Pro',
      ram: '12 GB',
      storage: '256 GB',
      cameraMain: '50 MP OIS',
      cameraUltrawide: '50 MP',
      frontCamera: '32 MP',
      battery: '5000 mAh, 45W',
      os: 'Android 14 (Nothing OS 2.5)',
      weight: '190 g',
      protection: 'Gorilla Glass 5',
    },
    stock: 18,
  },
  {
    sku: 'SM-HUAWEI-P60PRO',
    name: 'Huawei P60 Pro',
    brand: 'Huawei',
    categorySlug: 'smartphones',
    priceCents: 599900,
    description:
      'Huawei com câmera teleobjetiva periscópio de 48MP e estabilização de 3 eixos, fotografia noturna excepcional.',
    specifications: {
      screen: '6.67" LTPO OLED FHD+ 120Hz',
      processor: 'Snapdragon 8+ Gen 1',
      ram: '12 GB',
      storage: '512 GB',
      cameraMain: '48 MP (RYYB, f/1.4)',
      cameraUltrawide: '13 MP',
      cameraTelephoto: '48 MP periscópio (3.5x)',
      frontCamera: '13 MP',
      battery: '4815 mAh, 88W',
      os: 'EMUI 13 (sem serviços Google)',
      weight: '200 g',
      protection: 'IP68',
    },
    stock: 9,
  },
  {
    sku: 'SM-MOTOROLA-RAZR40',
    name: 'Motorola Razr 40',
    brand: 'Motorola',
    categorySlug: 'smartphones',
    priceCents: 349900,
    description:
      'Smartphone dobrável flip com tela externa de 1.5", compacto e elegante.',
    specifications: {
      screen: '6.9" pOLED FHD+ 144Hz (dobrável)',
      screenExternal: '1.5" OLED',
      processor: 'Snapdragon 7 Gen 1',
      ram: '8 GB',
      storage: '256 GB',
      cameraMain: '64 MP OIS',
      cameraUltrawide: '13 MP',
      frontCamera: '32 MP',
      battery: '4200 mAh, 30W',
      os: 'Android 13',
      weight: '188 g',
      protection: 'IP52',
    },
    stock: 11,
  },
  {
    sku: 'SM-SAMSUNG-ZFLIP6',
    name: 'Samsung Galaxy Z Flip6',
    brand: 'Samsung',
    categorySlug: 'smartphones',
    priceCents: 649900,
    description:
      'Dobrável flip com Snapdragon 8 Gen 3, tela externa de 3.4" e câmera de 50MP.',
    specifications: {
      screen: '6.7" Dynamic AMOLED 2X FHD+ 120Hz (dobrável)',
      screenExternal: '3.4" Super AMOLED',
      processor: 'Snapdragon 8 Gen 3 for Galaxy',
      ram: '12 GB',
      storage: '256 GB',
      cameraMain: '50 MP OIS',
      cameraUltrawide: '12 MP',
      frontCamera: '10 MP',
      battery: '4000 mAh, 25W',
      os: 'Android 14 (One UI 6.1.1)',
      weight: '187 g',
      protection: 'IP48, Armor Aluminum',
    },
    stock: 13,
  },
  {
    sku: 'SM-ONEPLUS-12',
    name: 'OnePlus 12',
    brand: 'OnePlus',
    categorySlug: 'smartphones',
    priceCents: 549900,
    description:
      'OnePlus com Hasselblad, carregamento de 100W e tela QHD+ de 120Hz, performance e bateria espetaculares.',
    specifications: {
      screen: '6.82" LTPO AMOLED QHD+ 120Hz',
      processor: 'Snapdragon 8 Gen 3',
      ram: '16 GB',
      storage: '512 GB',
      cameraMain: '50 MP Sony LYT-808 OIS',
      cameraUltrawide: '48 MP',
      cameraTelephoto: '64 MP (3x) Hasselblad',
      frontCamera: '32 MP',
      battery: '5400 mAh, 100W',
      os: 'Android 14 (OxygenOS 14)',
      weight: '220 g',
      protection: 'IP65, Gorilla Glass Victus 2',
    },
    stock: 14,
  },
  {
    sku: 'SM-REALME-GT6',
    name: 'Realme GT 6',
    brand: 'Realme',
    categorySlug: 'smartphones',
    priceCents: 279900,
    description:
      'Realme com Snapdragon 8s Gen 3 e tela LTPO de 120Hz, desempenho flagship por preço intermediário.',
    specifications: {
      screen: '6.78" LTPO AMOLED FHD+ 120Hz',
      processor: 'Snapdragon 8s Gen 3',
      ram: '12 GB',
      storage: '256 GB',
      cameraMain: '50 MP OIS',
      cameraUltrawide: '8 MP',
      cameraTelephoto: '50 MP (2x)',
      frontCamera: '32 MP',
      battery: '5500 mAh, 120W',
      os: 'Android 14 (Realme UI 5)',
      weight: '199 g',
      protection: 'Gorilla Glass Victus 2',
    },
    stock: 26,
  },
  {
    sku: 'SM-INFINIX-HOT50',
    name: 'Infinix Hot 50',
    brand: 'Infinix',
    categorySlug: 'smartphones',
    priceCents: 109900,
    description:
      'Entrada com tela de 120Hz e bateria de 5000mAh, o mais acessível para quem precisa do básico com qualidade.',
    specifications: {
      screen: '6.78" IPS FHD+ 120Hz',
      processor: 'MediaTek Helio G81',
      ram: '6 GB',
      storage: '128 GB (microSD)',
      cameraMain: '50 MP',
      cameraAux: '2 MP',
      frontCamera: '8 MP',
      battery: '5000 mAh, 18W',
      os: 'Android 14',
      weight: '187 g',
      protection: 'IP54',
    },
    stock: 50,
  },
  {
    sku: 'SM-APPLE-IPHONE14',
    name: 'Apple iPhone 14',
    brand: 'Apple',
    categorySlug: 'smartphones',
    priceCents: 499900,
    description:
      'iPhone 14 com chip A15, câmera de 12MP com estabilização por deslocamento de sensor.',
    specifications: {
      screen: '6.1" Super Retina XDR OLED',
      processor: 'Apple A15 Bionic',
      ram: '6 GB',
      storage: '128 GB',
      cameraMain: '12 MP (f/1.5)',
      cameraUltrawide: '12 MP',
      frontCamera: '12 MP',
      battery: '3279 mAh',
      os: 'iOS 17',
      weight: '172 g',
      protection: 'IP68, Ceramic Shield',
    },
    stock: 19,
  },
  {
    sku: 'SM-SAMSUNG-M15',
    name: 'Samsung Galaxy M15',
    brand: 'Samsung',
    categorySlug: 'smartphones',
    priceCents: 129900,
    description:
      'Bateria gigante de 6000mAh, tela Super AMOLED e atualizações longas — ideal para uso intenso.',
    specifications: {
      screen: '6.5" Super AMOLED FHD+ 90Hz',
      processor: 'MediaTek Dimensity 6100+',
      ram: '8 GB',
      storage: '128 GB (microSD)',
      cameraMain: '50 MP',
      cameraUltrawide: '5 MP',
      cameraMacro: '2 MP',
      frontCamera: '13 MP',
      battery: '6000 mAh, 25W',
      os: 'Android 14 (One UI 6)',
      weight: '217 g',
      protection: 'Gorilla Glass 5',
    },
    stock: 45,
  },
];

const monitors: SeedProduct[] = [
  {
    sku: 'MN-LG-27UL850',
    name: 'Monitor LG 27UL850 4K',
    brand: 'LG',
    categorySlug: 'monitors',
    priceCents: 299900,
    description:
      'Monitor 4K UHD de 27 polegadas com painel IPS, 98% DCI-P3 e USB-C com carregamento, ideal para desenvolvedores.',
    specifications: {
      screen: '27" 4K UHD (3840x2160) IPS',
      refreshRate: '60 Hz',
      responseTime: '5 ms',
      colorGamut: '98% DCI-P3',
      ports: 'USB-C (PD 60W), DisplayPort, HDMI x2',
      heightAdjust: 'Sim',
      speakers: 'Sim (5W x2)',
      vesa: '100x100 mm',
    },
    stock: 20,
  },
  {
    sku: 'MN-DELL-U2723QE',
    name: 'Dell UltraSharp U2723QE',
    brand: 'Dell',
    categorySlug: 'monitors',
    priceCents: 389900,
    description:
      'Monitor 4K com painel IPS Black e hub USB-C, qualidade de cor excelente para quem trabalha com design.',
    specifications: {
      screen: '27" 4K UHD (3840x2160) IPS Black',
      refreshRate: '60 Hz',
      responseTime: '5 ms',
      colorGamut: '100% sRGB, 98% DCI-P3',
      ports: 'USB-C (PD 90W), DisplayPort, HDMI, RJ45, USB-A x5',
      heightAdjust: 'Sim (150mm)',
      speakers: 'Não',
      vesa: '100x100 mm',
    },
    stock: 12,
  },
  {
    sku: 'MN-SAMSUNG-ODYSSEY-G5',
    name: 'Monitor Samsung Odyssey G5 27',
    brand: 'Samsung',
    categorySlug: 'monitors',
    priceCents: 189900,
    description:
      'Monitor curvo 1440p de 165Hz com 1ms, perfeito para gaming e desenvolvimento com muito espaço.',
    specifications: {
      screen: '27" QHD (2560x1440) VA curvo 1000R',
      refreshRate: '165 Hz',
      responseTime: '1 ms',
      colorGamut: '90% DCI-P3',
      ports: 'DisplayPort 1.2, HDMI 1.4 x2',
      heightAdjust: 'Sim',
      speakers: 'Não',
      vesa: '75x75 mm',
    },
    stock: 24,
  },
  {
    sku: 'MN-ASUS-PROART-PA278QV',
    name: 'ASUS ProArt PA278QV',
    brand: 'ASUS',
    categorySlug: 'monitors',
    priceCents: 219900,
    description:
      'Monitor profissional calibrado de fábrica com 100% sRGB e 100% Rec.709, ideal para editores.',
    specifications: {
      screen: '27" WQHD (2560x1440) IPS',
      refreshRate: '75 Hz',
      responseTime: '5 ms',
      colorGamut: '100% sRGB, 100% Rec.709',
      ports: 'DisplayPort, HDMI, DVI-D, USB x4',
      heightAdjust: 'Sim',
      speakers: 'Sim (2W x2)',
      vesa: '100x100 mm',
    },
    stock: 15,
  },
  {
    sku: 'MN-GIGABYTE-M27Q',
    name: 'Gigabyte M27Q',
    brand: 'Gigabyte',
    categorySlug: 'monitors',
    priceCents: 249900,
    description:
      'Monitor 2K de 170Hz com painel SS IPS e KVM embutido, ótimo para setup duplo.',
    specifications: {
      screen: '27" QHD (2560x1440) SS IPS',
      refreshRate: '170 Hz',
      responseTime: '0.5 ms',
      colorGamut: '92% DCI-P3',
      ports: 'USB-C (PD 18W), DisplayPort 1.2, HDMI 2.0 x2, KVM',
      heightAdjust: 'Sim',
      speakers: 'Sim',
      vesa: '100x100 mm',
    },
    stock: 18,
  },
  {
    sku: 'MN-LG-24GN600',
    name: 'Monitor LG Ultragear 24GN600',
    brand: 'LG',
    categorySlug: 'monitors',
    priceCents: 109900,
    description:
      'Monitor gamer 144Hz FHD de 24 polegadas, excelente relação custo-benefício para jogos e trabalho.',
    specifications: {
      screen: '24" FHD (1920x1080) IPS',
      refreshRate: '144 Hz',
      responseTime: '1 ms',
      colorGamut: '99% sRGB',
      ports: 'DisplayPort 1.4, HDMI 2.0 x2',
      heightAdjust: 'Não',
      speakers: 'Não',
      vesa: '100x100 mm',
    },
    stock: 30,
  },
  {
    sku: 'MN-DELL-S2722QC',
    name: 'Dell 27 S2722QC 4K',
    brand: 'Dell',
    categorySlug: 'monitors',
    priceCents: 249900,
    description:
      'Monitor 4K de 27 polegadas com USB-C e som integrado, ótimo para produtividade e home office.',
    specifications: {
      screen: '27" 4K UHD (3840x2160) IPS',
      refreshRate: '60 Hz',
      responseTime: '4 ms',
      colorGamut: '99% sRGB',
      ports: 'USB-C (PD 65W), HDMI 2.0 x2, DisplayPort 1.4',
      heightAdjust: 'Sim',
      speakers: 'Sim (3W x2)',
      vesa: '100x100 mm',
    },
    stock: 16,
  },
  {
    sku: 'MN-SAMSUNG-VIEWFINITY-S8',
    name: 'Samsung ViewFinity S8 4K',
    brand: 'Samsung',
    categorySlug: 'monitors',
    priceCents: 279900,
    description:
      'Monitor 4K com modo profissional e calibração de cor, ótimo para criadores de conteúdo.',
    specifications: {
      screen: '27" 4K UHD (3840x2160) IPS',
      refreshRate: '60 Hz',
      responseTime: '5 ms',
      colorGamut: '98% DCI-P3',
      ports: 'USB-C (PD 90W), DisplayPort, HDMI x2, USB x3',
      heightAdjust: 'Sim',
      speakers: 'Não',
      vesa: '100x100 mm',
    },
    stock: 14,
  },
  {
    sku: 'MN-ACER-NITRO-XV272U',
    name: 'Acer Nitro XV272U',
    brand: 'Acer',
    categorySlug: 'monitors',
    priceCents: 159900,
    description:
      'Monitor QHD de 170Hz com IPS, HDR400 e boa cobertura de cor para jogos e produtividade.',
    specifications: {
      screen: '27" QHD (2560x1440) IPS',
      refreshRate: '170 Hz',
      responseTime: '1 ms',
      colorGamut: '95% DCI-P3',
      ports: 'DisplayPort 1.4, HDMI 2.0 x2, USB-B x2',
      heightAdjust: 'Sim',
      speakers: 'Sim (2W x2)',
      vesa: '100x100 mm',
    },
    stock: 21,
  },
  {
    sku: 'MN-LG-45GS95QE',
    name: 'Monitor LG UltraGear 45GS95QE OLED',
    brand: 'LG',
    categorySlug: 'monitors',
    priceCents: 849900,
    description:
      'Monitor curvo OLED ultrawide 45 polegadas 240Hz com contraste infinito — experiência imersiva máxima.',
    specifications: {
      screen: '45" UW-QHD+ (5120x1440) OLED curvo 800R',
      refreshRate: '240 Hz',
      responseTime: '0.03 ms',
      colorGamut: '98.5% DCI-P3',
      ports: 'HDMI 2.1 x2, DisplayPort 1.4, USB-C (PD 65W)',
      heightAdjust: 'Sim',
      speakers: 'Sim',
      vesa: '100x100 mm',
    },
    stock: 5,
  },
];

const accessories: SeedProduct[] = [
  {
    sku: 'AC-LOGITECH-MX-MASTER3S',
    name: 'Mouse Logitech MX Master 3S',
    brand: 'Logitech',
    categorySlug: 'accessories',
    priceCents: 54990,
    description:
      'Mouse profissional silencioso com rolagem MagSpeed e conexão em até 3 dispositivos, essencial para produtividade.',
    specifications: {
      type: 'Mouse sem fio Bluetooth/2.4GHz',
      dpi: '8000 DPI (8K)',
      battery: 'Bateria interna recarregável (70 dias)',
      buttons: '7 botões programáveis',
      silent: 'Sim',
      compatibility: 'Windows, macOS, Linux, iPadOS',
    },
    stock: 40,
  },
  {
    sku: 'AC-KEYCHRON-K8-PRO',
    name: 'Teclado Keychron K8 Pro',
    brand: 'Keychron',
    categorySlug: 'accessories',
    priceCents: 89900,
    description:
      'Teclado mecânico hot-swappable com switches Gateron, Bluetooth triplo e layout ABNT2 — favorito dos devs.',
    specifications: {
      type: 'Mecânico hot-swappable (75%)',
      switch: 'Gateron Pro Brown (tátil)',
      layout: 'ABNT2 (ISO)',
      connectivity: 'Bluetooth 5.1, USB-C, 2.4GHz (via adaptador)',
      battery: '4000 mAh',
      keycaps: 'PBT Double-shot',
    },
    stock: 33,
  },
  {
    sku: 'AC-SONY-WH1000XM5',
    name: 'Fone Sony WH-1000XM5',
    brand: 'Sony',
    categorySlug: 'accessories',
    priceCents: 299990,
    description:
      'Headphone com cancelamento de ruído líder de mercado e 30 horas de bateria, perfeito para focar programando.',
    specifications: {
      type: 'Headphone over-ear Bluetooth',
      anc: 'Cancelamento de ruído ativo (8 microfones)',
      battery: '30 horas (ANC ligado)',
      codecs: 'LDAC, AAC, SBC',
      multipoint: 'Sim (2 dispositivos)',
      charging: 'USB-C, carga rápida 3min=3h',
      weight: '250 g',
    },
    stock: 18,
  },
  {
    sku: 'AC-SAMSUNG-T7-1TB',
    name: 'SSD Externo Samsung T7 1TB',
    brand: 'Samsung',
    categorySlug: 'accessories',
    priceCents: 59990,
    description:
      'SSD portátil de 1TB com velocidades de até 1050 MB/s, compacto e robusto para backups e projetos.',
    specifications: {
      type: 'SSD externo NVMe',
      capacity: '1 TB',
      speed: 'até 1050 MB/s leitura, 1000 MB/s escrita',
      interface: 'USB 3.2 Gen 2 (USB-C)',
      protection: 'Alumínio, queda de 2m',
      encryption: 'AES 256-bit XTS',
      weight: '58 g',
    },
    stock: 27,
  },
  {
    sku: 'AC-UGREEN-65W-GAN',
    name: 'Carregador UGREEN 65W GaN',
    brand: 'UGREEN',
    categorySlug: 'accessories',
    priceCents: 14990,
    description:
      'Carregador GaN de 65W com 3 portas, carrega notebook, celular e fone ao mesmo tempo.',
    specifications: {
      type: 'Carregador GaN USB-C',
      power: '65W total',
      ports: '2x USB-C (65W máx), 1x USB-A',
      protocol: 'PD 3.0, QC 4.0+, PPS',
      size: 'Mini (48x52x28mm)',
      weight: '127 g',
    },
    stock: 60,
  },
  {
    sku: 'AC-WEBCAM-LOGITECH-C920',
    name: 'Webcam Logitech C920s Pro',
    brand: 'Logitech',
    categorySlug: 'accessories',
    priceCents: 44990,
    description:
      'Webcam Full HD 1080p com correção automática de luz, essencial para reuniões e lives de code.',
    specifications: {
      resolution: 'Full HD 1080p 30fps',
      lens: 'Carl Zeiss, campo de visão 78°',
      mic: 'Microfones estéreo duplos',
      autofocus: 'Sim',
      connection: 'USB-A',
    },
    stock: 22,
  },
  {
    sku: 'AC-ELGATO-STREAMDECK',
    name: 'Elgato Stream Deck MK.2',
    brand: 'Elgato',
    categorySlug: 'accessories',
    priceCents: 89900,
    description:
      'Painel de 15 botões programáveis para atalhos, scripts e automação de fluxo de trabalho.',
    specifications: {
      buttons: '15 teclas LCD',
      keys: 'Atalhos customizáveis por app',
      integration: 'OBS, VS Code, Discord, GitHub Actions',
      connection: 'USB-C',
      weight: '280 g',
    },
    stock: 14,
  },
  {
    sku: 'AC-MONITOR-STAND-ERGOTRON',
    name: 'Suporte Ergotron LX',
    brand: 'Ergotron',
    categorySlug: 'accessories',
    priceCents: 119990,
    description:
      'Braço articulado para monitor de até 11.3kg, libera espaço na mesa e melhora ergonomia.',
    specifications: {
      type: 'Braço articulado de mesa',
      capacity: 'até 11.3 kg',
      movement: 'Altura de 33cm, alcance de 66cm',
      vesa: '75x75 / 100x100 mm',
      clamp: 'Grampo de mesa ou grommet',
    },
    stock: 10,
  },
  {
    sku: 'AC-KINGSTON-DDR5-32GB',
    name: 'Memória Kingston Fury 32GB DDR5',
    brand: 'Kingston',
    categorySlug: 'accessories',
    priceCents: 74900,
    description:
      'Kit de memória DDR5 5600MHz para upgrade de notebook gamer e workstations, essencial para Docker e VMs.',
    specifications: {
      type: 'DDR5 SODIMM',
      capacity: '32 GB (2x16 GB)',
      speed: '5600 MHz CL40',
      voltage: '1.1V',
      compatibility: 'Notebooks DDR5',
    },
    stock: 25,
  },
  {
    sku: 'AC-SEAGATE-BARRACUDA-4TB',
    name: 'HD Seagate Barracuda 4TB',
    brand: 'Seagate',
    categorySlug: 'accessories',
    priceCents: 69900,
    description:
      'HD interno de 4TB para storage de projetos, backups e mídia, confiável para NAS e desktop.',
    specifications: {
      type: 'HD interno 3.5"',
      capacity: '4 TB',
      speed: '5400 RPM',
      cache: '256 MB',
      interface: 'SATA III 6Gb/s',
      warranty: '2 anos',
    },
    stock: 20,
  },
];

const allProducts = [...notebooks, ...smartphones, ...monitors, ...accessories];

async function main(): Promise<void> {
  console.log('Seeding database...');

  const categories = [
    { slug: 'notebooks', name: 'Notebooks' },
    { slug: 'smartphones', name: 'Smartphones' },
    { slug: 'monitors', name: 'Monitores' },
    { slug: 'accessories', name: 'Acessórios' },
  ];

  for (const category of categories) {
    await prisma.category.upsert({
      where: { slug: category.slug },
      update: { name: category.name },
      create: category,
    });
  }
  console.log(`Categories: ${categories.length}`);

  const demoEmail = process.env.SEED_DEMO_USER_EMAIL ?? 'demo@commerce.ai';
  const demoPassword = process.env.SEED_DEMO_USER_PASSWORD ?? 'demo1234';
  const passwordHash = await bcrypt.hash(demoPassword, 12);
  const demoUser = await prisma.user.upsert({
    where: { email: demoEmail },
    update: { passwordHash },
    create: {
      email: demoEmail,
      name: 'Demo Customer',
      passwordHash,
    },
  });
  console.log(`Demo user: ${demoUser.email} / ${demoPassword}`);

  let created = 0;
  let updated = 0;
  for (const p of allProducts) {
    const category = await prisma.category.findUniqueOrThrow({
      where: { slug: p.categorySlug },
    });
    const data: Prisma.ProductCreateInput = {
      sku: p.sku,
      name: p.name,
      brand: p.brand,
      description: p.description,
      priceCents: p.priceCents,
      specifications: p.specifications,
      category: { connect: { id: category.id } },
      inventory: { create: { quantity: p.stock } },
    };
    const existing = await prisma.product.findUnique({ where: { sku: p.sku } });
    if (existing) {
      await prisma.product.update({
        where: { sku: p.sku },
        data: {
          ...data,
          version: { increment: 1 },
        },
      });
      updated++;
    } else {
      await prisma.product.create({ data });
      created++;
    }
  }
  console.log(`Products: ${created} created, ${updated} updated (total ${allProducts.length})`);

  const total = await prisma.product.count();
  console.log(`Done. ${total} products in catalog.`);
}

main()
  .catch((err) => {
    console.error(err);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
